spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db20220623231619_high?TNS_ADMIN=C:/webAI_KGJ/Wallet_DB20220623231619
    username: admin
    password: 
